name: Windows

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build and test with Rake
      run: |
        ls C:\hostedtoolcache\windows\Ruby\2.6.5\x64\include\ruby-2.6.0
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake compile --trace
        bundle exec rake test
      shell: cmd
